name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Env
      env:
        LINKFREE_MONGO_CONNECTION_STRING: "mongodb://localhost:12345/test"
      run: echo "LINKFREE_MONGO_CONNECTION_STRING=$LINKFREE_MONGO_CONNECTION_STRING" >> "$GITHUB_ENV"
    - run: cat "$GITHUB_ENV"
    - name: Build the Docker image
      run: docker buildx build --secret id=gh,src=$GITHUB_ENV . --file Dockerfile
