name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Env
      run: echo "LINKFREE_MONGO_CONNECTION_STRING=${{ secrets.MONGO_SECRET }}" >> "$GITHUB_ENV"
    - name: Build the Docker image
      run: docker buildx build --secret id=gh,src=$GITHUB_ENV . --file Dockerfile
