name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        LINKFREE_MONGO_CONNECTION_STRING: "mongodb://localhost:12345/test"
      run: docker buildx build --secret id=gh,src=$GITHUB_ENV . --file Dockerfile --tag my-image-name:$(date +%s)
